### PR TITLE
Hi,Dr.Brain:

### PR DESCRIPTION
**Pull request by 12301112-YouCheng**
I'm very glad to choose your courses(Android and SPA). I like your class
very much and I find that I can learn much knowledge and something
different from chinese teacher. Moreover actually, I plan to apply for
post-graduate study in the u.s. So I'd like to ask your help to write a
recommendation for me. I will do appreciate your help.

### CODE REVIEW

**Comment by Bansenauer-Cascadia** [comment]
Thank you for you feedback on the courses. I would be happy to write a recommendation letter for you. Please send me more information about your program and the date for your application submission.

**Comment by Bansenauer-Cascadia** [comment]
# Code Review

**Complete and correct code:**

---
- add a text box to enter the party size 

**Incorrect or missing code:**

---
- include an additional strings.xml file for Chinese localization
- calculate the amount owed per person (divide by zero check) 
- account for invalid user entries 
- update the total when the party size text is changed (event handler)

(only one file - the layout for activity_main.xml -  showed as changed)

**Comment by 12301112-YouCheng** [comment]
It's my honor to get your help. I appreciate you very much.
I want to study in California, you know, it's every software engineer's dream. UCB is my dream school, but you know it's very difficult to apply for a chinese student, I will try my best. Of course other Universities are also very excellent such as California Institute of Technology, Carnegie Mellon University, University of Washington and UCLA. I also want to study in these universities.
I plan to apply for eight universities, different universities has different date for application submission. However most of them is October or November. Before that, I will tell them your email address, at that time, you will get a email with a link to write a recommendation letter. So could you tell me your email address?

在2015-03-26 16:48:18，游程12301112@bjtu.edu.cn写道：

Thank you for you feedback on the courses. I would be happy to write a recommendation letter for you. Please send me more information about your program and the date for your application submission.

**Comment by Bansenauer-Cascadia** [comment]
It sounds like you have a good plan. Please have them send me information to this email address

bbansenauer@cascadia.edumailto:bbansenauer@cascadia.edu

Best regards,

Brian
On Apr 5, 2015, at 10:13 PM, 12301112-YouCheng <notifications@github.com<mailto:notifications@github.com>> wrote:

It's my honor to get your help. I appreciate you very much.
I want to study in California, you know, it's every software engineer's dream. UCB is my dream school, but you know it's very difficult to apply for a chinese student, I will try my best. Of course other Universities are also very excellent such as California Institute of Technology, Carnegie Mellon University, University of Washington and UCLA. I also want to study in these universities.
I plan to apply for eight universities, different universities has different date for application submission. However most of them is October or November. Before that, I will tell them your email address, at that time, you will get a email with a link to write a recommendation letter. So could you tell me your email address?

在2015-03-26 16:48:18，游程12301112@bjtu.edu.cnmailto:12301112@bjtu.edu.cn写道：

Thank you for you feedback on the courses. I would be happy to write a recommendation letter for you. Please send me more information about your program and the date for your application submission.

**Comment by 12301112-YouCheng** [comment]
Ok, I will tell them as you say, Thank you very much.

在2015-04-06 23:18:58，游程12301112@bjtu.edu.cn写道：

It sounds like you have a good plan. Please have them send me information to this email address

bbansenauer@cascadia.edumailto:bbansenauer@cascadia.edu

Best regards,

Brian
On Apr 5, 2015, at 10:13 PM, 12301112-YouCheng <notifications@github.com<mailto:notifications@github.com>> wrote:

It's my honor to get your help. I appreciate you very much.
I want to study in California, you know, it's every software engineer's dream. UCB is my dream school, but you know it's very difficult to apply for a chinese student, I will try my best. Of course other Universities are also very excellent such as California Institute of Technology, Carnegie Mellon University, University of Washington and UCLA. I also want to study in these universities.
I plan to apply for eight universities, different universities has different date for application submission. However most of them is October or November. Before that, I will tell them your email address, at that time, you will get a email with a link to write a recommendation letter. So could you tell me your email address?

在2015-03-26 16:48:18，游程12301112@bjtu.edu.cnmailto:12301112@bjtu.edu.cn写道：

Thank you for you feedback on the courses. I would be happy to write a recommendation letter for you. Please send me more information about your program and the date for your application submission.

**Pull request closed without merging**
