### PR TITLE
Mission Complete

### PR DESCRIPTION
**Pull request by wyw**
- Add another text box to enter the number of people eating. If the user enters the number of people in the party (more than one), calculate and display the amount owed by each person if the total bill (amount + tip) were to be split evenly among the party members.
- Include the localization for China.

### CODE REVIEW

**Comment by Bansenauer-Cascadia** [comment]
# Code Review

**Complete and correct code to:**

---
- add a text box to enter the party size 
- calculate the amount owed per person (divide by zero check)
- account for invalid user entries 
- update the total when the party size text is changed (event handler)

**Incorrect or missing code to:**

---
- include an additional strings.xml file for Chinese localization

**Comment by wyw** [comment]
Sir, there may be some thing wrong or mistake when I commit the source code, maybe I forgot check the radiobutton of strings.xml. I have the screen capture of the string.xml file on my laptop when it was created. The link: http://pan.baidu.com/s/1pJFm0ll . You could also check my project folder next class. Thanks. :<

**Comment by Bansenauer-Cascadia** [comment]
# Code Review

**Complete and correct code to:**

---
- add a text box to enter the party size 
- calculate the amount owed per person (divide by zero check)
- account for invalid user entries 
- update the total when the party size text is changed (event handler)
- include an additional strings.xml file for Chinese localization (demonstrated via screenshot - email 3/21)

**Comment by Bansenauer-Cascadia** [comment]
Yuanwei,

Ok - I have corrected your code review and the grade. You may have forgotten to add the localization folder to your repository before pushing.

Brian
On Mar 21, 2015, at 12:45 AM, Yuanwei Wu <notifications@github.com<mailto:notifications@github.com>> wrote:

Sir, there may be some thing wrong or mistake when I commit the source code, maybe I forgot check the radiobutton of strings.xml. I have the screen capture of the string.xml file on my laptop when it was created. The link: http://pan.baidu.com/s/1pJFm0ll . You could also check my project folder next class. Thanks. :<

**Comment by Bansenauer-Cascadia** [comment]
Ok - I have corrected your code review and the grade. You may have forgotten to add the localization folder to your repository before pushing.

**Comment by wyw** [comment]
Sir,
Most of my classmates told me that they have already commited and pushed the strings.xml for localization(may be not selected the localization folder) , but not successfully been saw at the Github.
Maybe other students that missing the strings.xml for localization may have the same situation as mine.

在2015-03-22 12:23:21，武元炜wuyuanwei@bjtu.edu.cn写道：

Ok - I have corrected your code review and the grade. You may have forgotten to add the localization folder to your repository before pushing.

**Pull request closed without merging**
