### PR TITLE
this is my homework 12301172 - qinshaojian

### PR DESCRIPTION
**Pull request by 12301172**
this is my homework

### CODE REVIEW

**Comment by Bansenauer-Cascadia** [comment]
# Code Review

**Complete and correct code to:**

---
- add a text box to enter the party size 
- button event handlers

**Incorrect or missing code to:**

---
- update the total when the party size text is changed (event handler for onTextChanged missing)
- account for invalid user entries 
- calculate the amount owed per person (divide by zero check)
- include an additional strings.xml file for Chinese localization

**Comment by 12301172** [comment]
1.you cilck the button catculate it will changed（I think this two function are the same）
2.in the activity_main.xml I designed the text just accept a number
android:numeric="integer"
3.I designed if number>1 it go to catculate.:(I think I need to change it to >=)
if(number>1){
                    average15 = billAmount*0.15;
                    average15 +=billAmount;
                    average15=average15/number;
                    Average15MoneyTextView.setText(currencyFormat.format(average15));
                    average = billAmount \* customPercent;
                    average += billAmount;
                   average=average/number;
                   AverageMoneyTextView.setText(currencyFormat.format(average));
                }
Q:what time need I give the correct one to you?

**Comment by 12301172** [comment]
1.you cilck the button catculate it will changed（I think this two function are the same）
2.in the activity_main.xml I designed the text just accept a number
android:numeric="integer"
3.I designed if number>1 it go to catculate.:(I think I need to change it to >=)
final Button catculator = (Button)findViewById(R.id.catculator);
-        catculator.setOnClickListener(new View.OnClickListener() {
-            @Override
-            public void onClick(View view) {
  +
-                double average15,average;
-                int number = Integer.parseInt(customerNumberTextView.getText().toString());
-                if(number>1){
-                    average15 = billAmount*0.15;
-                    average15 +=billAmount;
-                    average15=average15/number;
-                    Average15MoneyTextView.setText(currencyFormat.format(average15));
  +
-                    average = billAmount \* customPercent;
-                    average += billAmount;
-                    average=average/number;
-                    AverageMoneyTextView.setText(currencyFormat.format(average));
  +
  +
-                }
-            }
-        });‍
  ‍
  4.I design a button to translate the language :
  final Button translate = (Button)findViewById(R.id.translate);
-        translate.setOnClickListener(new View.OnClickListener() {
-            @Override
-            public void onClick(View view) {
-                if(TranslateState==1){
-                    amountTextView.setText("花费");
-                    customPercentTextView.setText("小费率");
-                    tipTextView.setText("小费");
-                    totalTextView.setText("总花费");
-                    NumberTextView.setText("人数");
-                    AverageTextView.setText("平均花费");
-                    catculator.setText("计算");
-                    translate.setText("翻译成英文");
-                    TranslateState=2;
-                }else  if (TranslateState==2){
-                    amountTextView.setText("Amount");
-                    customPercentTextView.setText("Custom %");
-                    tipTextView.setText("Tip");
-                    totalTextView.setText("Total");
-                    NumberTextView.setText("Number");
-                    AverageTextView.setText("Average");
-                    catculator.setText("catculate");
-                    translate.setText("translate to Chinese");
-                    TranslateState=1;
-                }
-            }
-        });‍

------------------ 原始邮件 ------------------
发件人: "Dr. Brian Bansenauer";notifications@github.com;
发送时间: 2015年3月20日(星期五) 晚上11:23
收件人: "MobileApps-BJTU/tip-calculator"tip-calculator@noreply.github.com; 
抄送: "Shao"356533308@qq.com; 
主题: Re: [tip-calculator] this is my homework 12301172 - qinshaojian (#50)

Code Review

Complete and correct code to:

add a text box to enter the party size 

button event handlers

Incorrect or missing code to:

update the total when the party size text is changed (event handler for onTextChanged missing)

account for invalid user entries 

calculate the amount owed per person (divide by zero check)

include an additional strings.xml file for Chinese localization

**Comment by Bansenauer-Cascadia** [comment]
# Code Review

I have reviewed your comments and see that I missed some of your credit.
Some code is still incomplete. The event handler would update your totals when the user enters a new value for the party size (not just clicking the button.) The translate button is interesting, but not standard for localization in android.

**Complete and correct code:**

---
- add a text box to enter the party size 
- calculate the amount owed per person (divide by zero check)
- account for invalid user entries 

**Incorrect or missing code:**

---
- include an additional strings.xml file for Chinese localization
- update the total when the party size text is changed (event handler)
- divide by zero test limited to button click

**Pull request closed without merging**
