### PR TITLE
12301117_ChenRuonan

### PR DESCRIPTION
**Pull request by 12301117-ChenRuonan**
Sry, I don't know I have to pull beforeTAT

### CODE REVIEW

**Comment by Bansenauer-Cascadia** [comment]
# Code Review

**Complete and correct code to:**

---
- add a text box to enter the party size 
- calculate the amount owed per person (divide by zero check)
- account for invalid user entries 
- update the total when the party size text is changed (event handler)

**Incorrect or missing code to:**

---
- include an additional strings.xml file for Chinese localization

**Comment by 12301117-ChenRuonan** [comment]
Sry,But I have finished localization already I remembered in my computer, I don't know what happened after pushed it onto github〒_〒 I'll check it after I go back to Beijing from Wuhan, So would it effect the grade?

**Comment by Bansenauer-Cascadia** [comment]
You may have forgotten to add the localization folder to your repository before pushing. Please send me a screen-shot of your localization folder with a date stamp and so I can include this in your grade.

**Comment by 12301117-ChenRuonan** [comment]
This is the screen-shot with a time stamp of this localization‍ folder.

------------------ 原始邮件 ------------------
发件人: "Dr. Brian Bansenauer";notifications@github.com;
发送时间: 2015年3月22日(星期天) 中午12:26
收件人: "MobileApps-BJTU/tip-calculator"tip-calculator@noreply.github.com; 
抄送: "勇敢的小孩"1198974650@qq.com; 
主题: Re: [tip-calculator] 12301117_ChenRuonan (#43)

You may have forgotten to add the localization folder to your repository before pushing. Please send me a screen-shot of your localization folder with a date stamp and so I can include this in your grade.

**Pull request closed without merging**
